import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { setTimeout as delay } from 'node:timers/promises';
import puppeteer, { type ElementHandle } from 'puppeteer-core';
import type { Studio } from '@/main/services/studio';

/** Real Electron UI journey in a fresh BES_TEST root. The only business writes
 * are ordinary hit-tested mouse/keyboard input. Service/file reads assert IDs,
 * revisions, and immutability; window sizing is the existing desktop test API. */
export async function runManagementArchiveJourney(studio: Studio) {
  assert.equal(process.env.BES_TEST, '1');
  assert.equal(path.resolve(studio.root), path.resolve(process.env.BES_DATA || ''));
  assert.equal(studio.projects.length, 0); assert.equal(studio.runs.length, 0);
  const report: any = { passed: false, processId: process.pid, startedAt: new Date().toISOString(), inputOrigin: 'empty synthetic root; normal hit-tested production UI', steps: [], layouts: [], pageErrors: [], dialogs: [] };
  const proof = path.join(studio.root, 'management-archive'); await mkdir(proof);
  const save = () => writeFile(path.join(studio.root, 'management-archive-detail.json'), JSON.stringify(report, null, 2));
  const [port, endpoint] = (await readFile(path.join(studio.root, 'DevToolsActivePort'), 'utf8')).trim().split(/\r?\n/);
  const browser = await puppeteer.connect({ browserWSEndpoint: `ws://127.0.0.1:${port}${endpoint}`, defaultViewport: null });
  const page = await browser.waitForTarget(t => t.url().includes('/main_window/index.html')).then(t => t.page()); assert(page);
  const window = studio.window.window; window.show(); window.focus();
  page.on('pageerror', e => report.pageErrors.push(e instanceof Error ? e.message : String(e)));
  // Observe native dialogs but never auto-accept them or change app semantics.
  page.on('dialog', d => { report.dialogs.push({ type: d.type(), message: d.message() }); void save(); });
  const server = createServer((req, res) => { res.setHeader('content-type', 'text/html;charset=utf-8'); res.setHeader('cache-control', 'no-store'); res.end(`<!doctype html><meta charset="utf-8"><title>合成管理来源 ${req.url === '/second' ? '第二页' : '首页'}</title><style>body{font:20px system-ui;padding:32px}a,button{margin:12px}</style><h1>合成管理来源</h1><p id="amount">12.00</p><a href="/second">第二页</a><a href="/">首页</a><button onclick="document.querySelector('#amount').textContent='13.00'">更新金额</button>`); });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
  const address = server.address(); assert(address && typeof address !== 'string'); const origin = `http://127.0.0.1:${address.port}`;
  async function until<T>(read: () => Promise<T> | T, accept: (x: T) => boolean, label: string, timeout = 20000): Promise<T> {
    const end = Date.now() + timeout; let last: T | undefined;
    while (Date.now() < end) { last = await read(); if (accept(last)) return last; await delay(60); }
    throw new Error(`Management journey timeout: ${label}; last=${JSON.stringify(last)}`);
  }
  async function control(kind: 'button' | 'input' | 'summary' | 'checkbox', name: string, scope = ''): Promise<ElementHandle<Element>> {
    const handle = await page!.waitForFunction((kind, name, scope) => {
      const root = scope ? document.querySelector(scope) : document;
      if (!root) return null;
      const usable = (e: Element) => !!e.getClientRects().length && !e.closest('[hidden],[inert],fieldset[disabled]') && !(e as HTMLButtonElement).disabled;
      let candidates: Element[] = [];
      if (kind === 'button') candidates = [...root.querySelectorAll('button')].filter(e => (e.textContent?.trim() === name || e.getAttribute('aria-label') === name));
      else if (kind === 'summary') candidates = [...root.querySelectorAll('summary')].filter(e => e.textContent?.trim().startsWith(name));
      else if (kind === 'checkbox') candidates = [...root.querySelectorAll('label')].filter(e => e.textContent?.trim() === name).flatMap(e => [...e.querySelectorAll('input[type=checkbox]')]);
      else candidates = [...root.querySelectorAll('input,textarea,select')].filter(e => e.getAttribute('aria-label') === name || e.closest('label')?.firstChild?.textContent?.trim() === name);
      return candidates.find(usable) || null;
    }, { timeout: 20000 }, kind, name, scope);
    const element = handle.asElement(); assert(element, `Control ${name}`); return element as ElementHandle<Element>;
  }
  async function hit(element: ElementHandle<Element>, clickCount = 1) {
    await page!.bringToFront(); window.focus();
    await element.evaluate(e => e.scrollIntoView({ block: 'center', inline: 'nearest' }));
    assert(await element.evaluate(e => { const r = e.getBoundingClientRect(), hit = document.elementFromPoint(r.x + r.width / 2, r.y + r.height / 2); return !!hit && (hit === e || e.contains(hit)); }), 'Actual pointer hit-test');
    await element.click({ count: clickCount });
  }
  async function click(name: string, scope = '') { await hit(await control('button', name, scope)); await delay(130); }
  async function fill(name: string, value: string, scope = '') { const e = await control('input', name, scope); await hit(e); await page!.keyboard.down('Control'); await page!.keyboard.press('a'); await page!.keyboard.up('Control'); await page!.keyboard.press('Backspace'); await e.type(value); assert.equal(await e.evaluate(e => (e as HTMLInputElement).value), value); }
  async function disclose(name: string, scope = '') { const e = await control('summary', name, scope); if (!await e.evaluate(e => (e.parentElement as HTMLDetailsElement).open)) await hit(e); }
  async function check(name: string, scope = '') { const box = await control('checkbox', name, scope); if (!await box.evaluate(e => (e as HTMLInputElement).checked)) await hit(box); await delay(130); }
  const text = (scope = 'body') => page!.$eval(scope, e => (e as HTMLElement).innerText);
  const hasText = (value: string, scope = 'body') => until(() => text(scope), t => t.includes(value), value);
  const absent = (selector: string) => page!.waitForFunction(s => !document.querySelector(s), {}, selector);
  const idle = () => page!.waitForFunction(() => !document.querySelector('.statusbar')?.textContent?.includes('正在处理') && !document.querySelector('.management-panel[aria-busy=true],.archive-center[aria-busy=true],.recording-archive[aria-busy=true]'));
  const management = '[aria-label="项目与环境管理"]';
  const selectedProject = () => studio.projects.find(p => p.name === '管理验收主项目');
  let projectId = '', profileId = '', recordingId = '', fixedFile = '', fixedHash = '';
  const materialRoot = () => path.join(studio.root, 'projects', projectId, 'materials');
  const catalog = async () => JSON.parse(await readFile(path.join(materialRoot(), 'catalog.json'), 'utf8'));
  const currentDraft = async () => { const c = await catalog(); return JSON.parse(await readFile(path.join(materialRoot(), 'drafts', c.workingDraftId + '.json'), 'utf8')); };
  const hash = (b: Buffer) => createHash('sha256').update(b).digest('hex');
  async function originals(root: string, prefix = ''): Promise<Record<string, string>> { const out: Record<string, string> = {}; for (const entry of await readdir(root, { withFileTypes: true })) { const rel = prefix + entry.name; if (/^(index|replay-index)(\/|$)/.test(rel)) continue; if (entry.isDirectory()) Object.assign(out, await originals(path.join(root, entry.name), rel + '/')); else out[rel] = hash(await readFile(path.join(root, entry.name))); } return out; }
  async function mark(name: string) { report.steps.push({ name, at: new Date().toISOString() }); await page!.screenshot({ path: path.join(proof, String(report.steps.length).padStart(2, '0') + '-' + name + '.renderer.png') }); await save(); }
  async function layout(name: string, selector: string) {
    for (const [width, height] of [[1100, 760], [1450, 935]]) {
      window.setSize(width, height); await delay(250);
      const values = await page!.evaluate(selector => { const e = document.querySelector(selector)!; const r = e.getBoundingClientRect(); const stop = [...document.querySelectorAll('button')].filter(b => b.textContent?.trim() === '全局停止自动化' && b.getClientRects().length).at(-1); return { viewport: { width: innerWidth, height: innerHeight }, documentOverflow: document.documentElement.scrollWidth > innerWidth, bounds: { x: r.x, y: r.y, width: r.width, height: r.height, right: r.right, bottom: r.bottom }, ownOverflow: e.scrollWidth > e.clientWidth + 1, stop: !!stop && stop.getBoundingClientRect().height > 0 }; }, selector);
      report.layouts.push({ name, width, height, windowBounds: window.getBounds(), ...values });
      assert.equal(values.viewport.width, width); assert.equal(values.viewport.height, height); assert(!values.documentOverflow, `${name} no document overflow`); assert(!values.ownOverflow, `${name} no horizontal overflow`); assert(values.stop, 'Global safety stop remains reachable'); assert(values.bounds.right <= width + 1, `${name} fits actual window horizontally`); if (selector === management) assert(values.bounds.bottom <= height + 1, `${name} management viewport fits`); else { const container = await page!.$eval('.workspace-panel', e => { const r = e.getBoundingClientRect(); return { width: r.width, bottom: r.bottom }; }); assert(container.bottom <= height + 1, 'Archive scroll viewport fits'); assert(container.width > width * .5 && container.width > report.normalWorkspaceWidth, 'Archive expands beyond ordinary workspace while retaining live pane'); }
      await page!.screenshot({ path: path.join(proof, `${name}-${width}.renderer.png`) });
      if ((process.env.BES_MANAGEMENT_NATIVE_PAUSE === '1' && ['management-long-directory', 'archive-recording-detail'].includes(name) || process.env.BES_MANAGEMENT_NATIVE_PAUSE === 'archives' && name === 'archive-recording-detail')) { const marker = `${name}-${width}`; await writeFile(path.join(proof, 'awaiting-native.json'), JSON.stringify({ marker, processId: process.pid, windowBounds: window.getBounds(), uiUrl: page!.url() })); console.log('AWAITING_MANAGEMENT_NATIVE ' + marker); await until(async () => readFile(path.join(proof, marker + '.continue'), 'utf8').then(v => v === 'continue').catch(() => false), Boolean, 'native inspection ' + marker, 120000); }
    }
  }
  try {
    await click('新建项目'); await fill('项目名称', '管理验收主项目'); await fill('目录简介', '只使用普通界面完成目录与存档验收'); await click('创建项目'); await until(() => selectedProject(), Boolean, 'first project'); projectId = selectedProject()!.id; await idle();
    await click('项目与环境管理'); await fill('项目名称', '未保存的名称', management); await click('返回工作台'); await hasText('保留输入，还是放弃后继续？', management); await click('继续编辑', management); assert.equal(await (await control('input', '项目名称', management)).evaluate(e => (e as HTMLInputElement).value), '未保存的名称');
    await page.keyboard.press('Escape'); await hasText('保留输入，还是放弃后继续？', management); await click('放弃输入并继续', management); await absent('.management-panel'); await click('项目与环境管理'); assert.equal(await (await control('input', '项目名称', management)).evaluate(e => (e as HTMLInputElement).value), '管理验收主项目');
    await click('新建项目', management); await fill('项目名称', '取消的项目', management); await click('取消创建项目', management); await click('放弃输入并继续', management); assert.equal(studio.projects.length, 1); assert(!(await text(management)).includes('创建后先整理')); await mark('management-dirty-exit-and-create-cancel');
    // Artificial pre-commit refusal: no original service method is called until
    // the user retries. Count the exact object and restore the wrapper always.
    const originalUpdate = studio.updateProject; let releaseFailure: (() => void) | undefined;
    try {
      let attempts = 0; const held = new Promise<void>(resolve => { releaseFailure = resolve; });
      studio.updateProject = async body => { if (body.projectId !== projectId) return originalUpdate.call(studio, body); attempts++; await held; throw new Error('合成测试：提交前拒绝，请重试'); };
      await fill('目录简介', '故障后需要保留的目录输入', management); const saveButton = await control('button', '保存项目修改', management); await hit(saveButton, 2); await until(() => attempts, n => n === 1, 'injected request received');
      assert(await saveButton.evaluate(e => (e as HTMLButtonElement).disabled)); await click('返回工作台'); assert(await page.$('.management-panel')); assert.equal(attempts, 1); await mark('artificial-pending-save-blocks-exit'); releaseFailure!(); await hasText('合成测试：提交前拒绝', management);
      assert.equal(await (await control('input', '目录简介', management)).evaluate(e => (e as HTMLInputElement).value), '故障后需要保留的目录输入'); assert.equal(selectedProject()!.objective, '只使用普通界面完成目录与存档验收'); studio.updateProject = originalUpdate;
      await click('保存项目修改', management); await until(() => selectedProject()!.objective, s => s === '故障后需要保留的目录输入', 'normal retry after pre-commit refusal'); await idle(); report.injectedPrecommitRefusal = { target: projectId, attempts, durableWritesDuringRefusal: 0, retriedThroughUi: true };
      let lateAttempts = 0; const late = new Promise<void>(resolve => { releaseFailure = resolve; });
      studio.updateProject = async body => { if (body.projectId !== projectId) return originalUpdate.call(studio, body); lateAttempts++; await late; throw new Error('合成测试：旧编辑会话迟到失败'); };
      await fill('目录简介', '不会落盘的旧编辑会话', management); await click('保存项目修改', management); await until(() => lateAttempts, n => n === 1, 'late failure held'); await page.reload(); await page.waitForSelector('.evidence-strip'); await idle(); await click('项目与环境管理'); releaseFailure!(); await delay(300); assert(!(await text()).includes('合成测试：旧编辑会话迟到失败')); assert.equal(selectedProject()!.objective, '故障后需要保留的目录输入'); report.injectedLateFailure = { target: projectId, attempts: lateAttempts, interruptedBy: 'real renderer reload', leakedIntoNewSession: false }; await mark('artificial-precommit-error-retry-and-interruption');
    } finally { releaseFailure?.(); studio.updateProject = originalUpdate; }
    for (let i = 1; i <= 18; i++) { await click('新建项目', management); await fill('项目名称', `目录项目 ${String(i).padStart(2, '0')}`, management); await fill('目录简介', i === 18 ? '长名称和说明用于检查滚动，不是隐藏预置资料。'.repeat(8) : '合成目录', management); await click('创建项目', management); await until(() => studio.projects.length, n => n === i + 1, 'normal UI project creation'); await idle(); }
    report.createdProjectSelectionVisible = await until(() => page.$eval('.management-project-list', e => { const row = e.querySelector('[aria-pressed="true"]'); if (!row) return false; const r = row.getBoundingClientRect(), list = e.getBoundingClientRect(); return r.top >= list.top - 1 && r.bottom <= list.bottom + 1; }), Boolean, 'newly created project is visible in its directory');
    await layout('management-long-directory', management); await fill('搜索项目', '没有这个项目', management); await hasText('没有匹配的项目', management); await fill('搜索项目', '管理验收', management); await click('管理验收主项目 · 当前浏览', management); await fill('搜索项目', '', management); await mark('management-search-and-long-list');
    await click('添加登录环境', management); await fill('环境名称', '取消的环境', management); await click('取消创建环境', management); await click('放弃输入并继续', management); assert.equal(studio.profiles.length, 0);
    await click('添加登录环境', management); await fill('环境名称', '合成环境甲', management); await fill('环境登录入口', origin, management); await click('创建登录环境', management); await until(() => studio.profiles.length, n => n === 1, 'profile created'); profileId = studio.profiles[0].id; await idle(); const initialStorage = JSON.parse(JSON.stringify(studio.profiles[0]));
    await fill('环境名称', '合成环境甲已改名', management); await click('保存环境修改', management); await until(() => studio.profiles[0].name, s => s === '合成环境甲已改名', 'profile rename'); assert.equal(studio.profiles[0].id, profileId); assert.equal((studio.profiles[0] as any).partition, initialStorage.partition); assert.equal(studio.profiles[0].storageRef, initialStorage.storageRef);
    await fill('环境登录入口', 'javascript:alert(1)', management); await click('保存环境修改', management); await hasText('Error', management); assert.equal(await (await control('input', '环境登录入口', management)).evaluate(e => (e as HTMLInputElement).value), 'javascript:alert(1)'); await click('撤销环境输入', management); await idle(); await layout('management-profile-detail', management); await mark('profile-cancel-rename-invalid-url-recovery');
    await disclose('环境停用与删除', management); await click('停用环境', management); await hasText('录制、资料版本、来源与登录数据会保留', management); await click('取消', '[aria-label="确认管理操作"]'); assert.notEqual(studio.profiles[0].lifecycle, 'disabled'); await click('停用环境', management); await click('确认停用', '[aria-label="确认管理操作"]'); await until(() => studio.profiles[0].lifecycle, s => s === 'disabled', 'disabled profile'); await idle(); await disclose('环境停用与删除', management); await click('恢复环境', management); await until(() => studio.profiles[0].lifecycle, s => s !== 'disabled', 'restored profile'); await idle(); assert.deepEqual(studio.profiles[0].storageRef, initialStorage.storageRef); await mark('profile-disable-cancel-and-restore');
    await click('打开环境', management); await until(() => studio.state().session?.profileId, id => id === profileId, 'UI opens exact profile'); await idle(); await click('返回项目资料', management); await click('目录项目 01', management); assert.equal(studio.state().session?.projectId, projectId); await click('设为当前浏览项目', management); await idle(); await hasText('正在浏览其他项目', management); assert.equal(studio.state().session?.profileId, profileId); await click('管理验收主项目', management); await click('设为当前浏览项目', management); await idle(); await click('返回工作台'); await absent('.management-panel'); await mark('management-context-independent-of-live-browser');
    const live = await browser.waitForTarget(t => t.url().startsWith(origin)).then(t => t.page()); assert(live); await live.waitForSelector('#amount');
    const navigationState = studio.state().session!; const navigationPage = navigationState.pages.find(p => p.pageId === navigationState.selectedPageId)!; report.initialNavigationState = navigationPage;
    for (const [label, available] of [['后退', navigationPage.canGoBack], ['前进', navigationPage.canGoForward]] as const) { const observed: { svg: boolean; title: string | null; label: string | null; disabled: boolean } = await page.$eval('button[aria-label="' + label + '"]', (e: Element) => ({ svg: !!e.querySelector('svg'), title: e.getAttribute('title'), label: e.getAttribute('aria-label'), disabled: (e as HTMLButtonElement).disabled })); assert(observed.svg && observed.title === observed.label, label + ' real named icon'); assert.equal(observed.disabled, !available, label + ' matches actual page history'); }
    await click('新标签'); await until(() => studio.state().session?.pages.length, n => n === 2, 'blank no-history tab'); await idle(); for (const label of ['后退', '前进']) assert(await page.$eval(`button[aria-label="${label}"]`, e => (e as HTMLButtonElement).disabled), label + ' disabled for actual empty history'); const blankClose = await page.$$eval('button[aria-label^="关闭标签"]', es => es.at(-1)?.getAttribute('aria-label')); assert(blankClose); await click(blankClose); await until(() => studio.state().session?.pages.length, n => n === 1, 'blank page closed');

    await fill('网页地址', origin + '/second'); await click('前往'); await until(() => studio.state().session?.pages.find(p => p.pageId === studio.state().session?.selectedPageId)?.url, value => value === origin + '/second', 'second navigation'); await click('后退'); await until(() => studio.state().session?.pages.find(p => p.pageId === studio.state().session?.selectedPageId)?.url, value => value === origin + '/', 'back navigation'); await click('前进'); await until(() => studio.state().session?.pages.find(p => p.pageId === studio.state().session?.selectedPageId)?.url, value => value === origin + '/second', 'forward navigation');
    const afterHistory = studio.state().session!; assert.equal(afterHistory.profileId, profileId); assert.equal(afterHistory.selectedPageId, navigationPage.pageId); assert.equal(afterHistory.pages.find(p => p.pageId === navigationPage.pageId)!.targetId, navigationPage.targetId); report.historyTargetPreserved = { profileId, pageId: navigationPage.pageId, targetId: navigationPage.targetId };
    await hit(await control('input', '网页地址')); await page.keyboard.down('Shift'); await page.keyboard.press('Tab'); await page.keyboard.press('Tab'); await page.keyboard.up('Shift'); assert.equal(await page.evaluate(() => document.activeElement?.getAttribute('aria-label')), '后退'); await mark('keyboard-focus-reaches-back-icon');
    await click('新标签'); await until(() => studio.state().session?.pages.length, n => n === 2, 'new tab'); const closeLabel = await page.$$eval('button[aria-label^="关闭标签"]', es => es.at(-1)?.getAttribute('aria-label')); assert(closeLabel); const closeButton = await control('button', closeLabel); assert(await closeButton.evaluate(e => !!e.querySelector('svg') && e.getAttribute('title') === e.getAttribute('aria-label'))); await hit(closeButton); await until(() => studio.state().session?.pages.length, n => n === 1, 'close one page'); await click('恢复关闭的标签'); await until(() => studio.state().session?.pages.length, n => n === 2, 'restore one page'); const restoredClose = await page.$$eval('button[aria-label^="关闭标签"]', es => es.at(-1)?.getAttribute('aria-label')); assert(restoredClose); await click(restoredClose); await until(() => studio.state().session?.pages.length, n => n === 1, 'close restored page'); await mark('browser-real-icons-history-close-restore');
    await click('开始录制'); await until(() => studio.active?.capture, x => x === 'recording', 'recording ready'); await hasText('结束并封存'); await idle(); await click('新增保存点'); await page.waitForSelector('.material-card-list button'); if (!await page.$('[aria-label="编辑保存点"]')) await click('编辑保存点'); await fill('标题', '通过普通界面创建的保存点'); await fill('说明', '该来源仅存在于本轮合成实例'); await click('完成保存点编辑'); await click('结束并封存'); await until(() => studio.active, x => !x, 'sealed'); await hasText('录制已封存'); await idle(); recordingId = studio.runs[0].id; const originalBefore = await originals(path.join(studio.root, 'runs', recordingId));
    report.normalWorkspaceWidth = await page.$eval('.workspace-panel', e => e.getBoundingClientRect().width); const mountedEditor = await page.$('.material-workbench'); assert(mountedEditor);
    await click('存档'); await idle();
    const preferencesFile = path.join(studio.root, 'ui-preferences.json'); const readPreferences = async (): Promise<{ layout: Record<string, number[]> }> => { try { return JSON.parse(await readFile(preferencesFile, 'utf8')); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return { layout: {} }; throw error; } }; const preferencesBeforeDrag = await readPreferences();
    const separator = await page.$('[role="separator"][aria-label="调整工作台与浏览器宽度"]'); assert(separator); const splitPoint = await separator.evaluate(e => { const r = e.getBoundingClientRect(); return { x: r.x + r.width / 2, y: r.y + r.height / 2 }; }); await page.mouse.move(splitPoint.x, splitPoint.y); await page.mouse.down(); await page.mouse.move(splitPoint.x - 45, splitPoint.y, { steps: 8 }); await page.mouse.up(); const archivePreferences = await until(readPreferences, p => !!p.layout['workspace-archive'], 'archive drag preference'); assert.deepEqual(archivePreferences.layout.workspace, preferencesBeforeDrag.layout.workspace); report.archiveDragPreferences = { before: preferencesBeforeDrag, after: archivePreferences };
    await click('保存存档版本'); await fill('版本名称', '取消的存档范围'); await click('返回继续编辑'); await page.waitForFunction(() => document.querySelector('.material-workbench')?.getAttribute('data-view') === 'checkpoints'); assert(await mountedEditor.evaluate(e => e.isConnected && e === document.querySelector('.material-workbench')), 'Archive transition retains the exact editor element'); await until(() => page.$eval('.workspace-panel', e => e.getBoundingClientRect().width), width => Math.abs(width - report.normalWorkspaceWidth) < 2, 'ordinary workspace ratio restored'); report.archiveTransitionPreservedEditorAndRatio = true; assert.equal((await readdir(path.join(materialRoot(), 'revisions')).catch((error: NodeJS.ErrnoException) => { if (error.code === 'ENOENT') return []; throw error; })).filter(n => n.endsWith('.json')).length, 0); await click('存档'); await click('保存存档版本'); await fill('版本名称', '验收固定版本 V1'); await click('确认保存存档版本'); await hasText('已保存存档版本'); await idle(); const fixedNames = (await readdir(path.join(materialRoot(), 'revisions'))).filter(n => n.endsWith('.json')); assert.equal(fixedNames.length, 1); fixedFile = path.join(materialRoot(), 'revisions', fixedNames[0]); fixedHash = hash(await readFile(fixedFile)); const fixed = JSON.parse(await readFile(fixedFile, 'utf8')); await click('查看固定版本'); await hasText('存档 V1 · 只读'); assert.equal(await page.$$eval('[aria-label="固定版本只读"] [aria-label="编辑保存点"], [aria-label="固定版本只读"] [aria-label="编辑字段"]', e => e.length), 0); await layout('archive-fixed-detail', '.archive-center');
    const beforeMetadata = await catalog(); await fill('版本标签', '未保存的标签'); await page.keyboard.press('Tab'); await delay(200); assert.deepEqual(await catalog(), beforeMetadata); await click('工作副本'); await hasText('目录信息有未保存输入'); await click('取消目录修改'); await fill('版本标签', '固定版目录标签'); await click('保存目录信息'); await until(async () => (await catalog()).revisions[fixed.revisionId].name, s => s === '固定版目录标签', 'explicit metadata save'); assert.equal(hash(await readFile(fixedFile)), fixedHash);
    await disclose('版本标识与目录管理'); await click('隐藏版本'); await until(async () => (await catalog()).revisions[fixed.revisionId].hidden, Boolean, 'hidden fixed'); await page.reload(); await page.waitForSelector('.evidence-strip'); await idle(); await click('存档'); await hasText('还没有存档版本'); assert.equal(await page.$$eval('[aria-label="资料版本目录"] .archive-list-entry', es => es.length), 0); await check('显示已移除条目'); await click('查看固定版本'); await disclose('版本标识与目录管理'); await click('恢复版本'); await until(async () => (await catalog()).revisions[fixed.revisionId].hidden, x => !x, 'restore fixed'); await mark('fixed-readonly-explicit-save-hide-refresh-restore');
    await click('基于此版继续编辑'); await until(async () => (await currentDraft()).baseRevisionId, id => id === fixed.revisionId, 'derive preserves parent'); await page.waitForFunction(() => document.querySelector('.material-workbench')?.getAttribute('data-view') === 'checkpoints'); assert.equal(hash(await readFile(fixedFile)), fixedHash); await click('存档'); await click('工作副本'); const currentRow = await page.waitForFunction(() => [...document.querySelectorAll('[aria-label="工作副本目录"] .archive-list-entry')].find(e => e.textContent?.includes('当前工作副本'))?.querySelector('button')); await hit(currentRow.asElement() as ElementHandle<Element>); await fill('副本名称', '派生工作副本'); await click('保存目录信息'); await until(async () => Object.values((await catalog()).drafts).some((d: any) => d.name === '派生工作副本'), Boolean, 'derived label');
    for (let i = 0; i < 12; i++) { const before = Object.keys((await catalog()).drafts).length; await click('复制工作副本'); await until(async () => Object.keys((await catalog()).drafts).length, n => n === before + 1, 'copy UI'); await idle(); }
    await layout('archive-long-working-copies', '.archive-center'); await mark('derived-work-copy-and-long-list');
    const currentRowAfterCopies = await page.waitForFunction(() => [...document.querySelectorAll('[aria-label="工作副本目录"] .archive-list-entry')].find(e => e.textContent?.includes('当前工作副本'))?.querySelector('button')); await hit(currentRowAfterCopies.asElement() as ElementHandle<Element>);
    await disclose('副本标识与移除'); const removeCurrent = await page.$('[aria-label="工作副本详情"] button'); assert(removeCurrent); assert(await page.$eval('[aria-label="工作副本详情"]', e => [...e.querySelectorAll('button')].some(b => b.textContent === '移除副本' && b.disabled)), 'Current draft cannot be removed');
    const otherCopy = await page.waitForFunction(() => [...document.querySelectorAll('[aria-label="工作副本目录"] .archive-list-entry')].find(e => !e.textContent?.includes('当前工作副本'))?.querySelector('button')); await hit(otherCopy.asElement() as ElementHandle<Element>); await disclose('副本标识与移除'); const selectedCopyName = await (await control('input', '副本名称')).evaluate(e => (e as HTMLInputElement).value); await click('移除副本'); await until(async () => Object.values((await catalog()).drafts).filter((x: any) => x.hidden).length, n => n === 1, 'copy removed'); await check('显示已移除条目'); const hiddenCopy = await page.waitForFunction(() => [...document.querySelectorAll('[aria-label="工作副本目录"] .archive-list-entry')].find(e => e.textContent?.includes('已移除'))?.querySelector('button')); await hit(hiddenCopy.asElement() as ElementHandle<Element>); await disclose('副本标识与移除'); await click('恢复副本'); await until(async () => Object.values((await catalog()).drafts).filter((x: any) => x.hidden).length, n => n === 0, 'copy restored'); report.restoredCopyName = selectedCopyName;
    await click('原始录制'); await until(() => page.$('[aria-label="原始录制存档"]'), Boolean, 'recordings visible'); await click('查看录制详情'); await layout('archive-recording-detail', '.archive-center'); await click('查看使用位置'); await hasText('存档 V1', '[aria-label="录制使用位置"]');
    const recordingCatalogBefore = await catalog(); await fill('录制名称', '尚未保存的录制目录'); await page.keyboard.press('Tab'); await delay(200); assert.deepEqual(await catalog(), recordingCatalogBefore); await click('工作副本'); await hasText('录制目录有未保存输入'); await click('取消录制修改');
    const originalManage = studio.materials.service.manageCatalog; let releaseCatalog: (() => void) | undefined;
    try {
      let attempts = 0; const held = new Promise<void>(resolve => { releaseCatalog = resolve; });
      studio.materials.service.manageCatalog = async (owner, input) => { if (owner !== projectId || input.kind !== 'recordings' || input.id !== recordingId) return originalManage.call(studio.materials.service, owner, input); attempts++; await held; throw new Error('合成测试：录制目录提交前拒绝'); };
      await fill('录制名称', '明确保存的合成录制'); await click('保存录制目录'); await until(() => attempts, n => n === 1, 'held recording save'); assert(await page.$eval('button[aria-label="刷新录制目录"]', e => (e as HTMLButtonElement).disabled)); await click('工作副本'); await hasText('正在处理录制操作'); assert.equal(attempts, 1); await mark('artificial-recording-save-pending'); releaseCatalog!(); await hasText('合成测试：录制目录提交前拒绝'); assert.equal(await (await control('input', '录制名称')).evaluate(e => (e as HTMLInputElement).value), '明确保存的合成录制'); assert.deepEqual(await catalog(), recordingCatalogBefore); studio.materials.service.manageCatalog = originalManage;
      await click('保存录制目录'); await until(async () => (await catalog()).recordings[recordingId]?.name, s => s === '明确保存的合成录制', 'explicit recording retry saved'); report.injectedRecordingPrecommitRefusal = { target: recordingId, attempts, durableWritesDuringRefusal: 0, retriedThroughUi: true };
    } finally { releaseCatalog?.(); studio.materials.service.manageCatalog = originalManage; }
    await disclose('录制管理与诊断'); await click('隐藏录制'); await until(async () => (await catalog()).recordings[recordingId]?.hidden, Boolean, 'hidden recording'); await page.reload(); await page.waitForSelector('.evidence-strip'); await idle(); await click('存档'); await click('原始录制'); await hasText('没有匹配的录制'); await check('显示已隐藏录制'); await click('查看录制详情'); await disclose('录制管理与诊断'); await click('恢复录制'); await until(async () => (await catalog()).recordings[recordingId]?.hidden, x => !x, 'restore recording'); await click('查看使用位置'); await hasText('存档 V1', '[aria-label="录制使用位置"]'); await mark('recording-explicit-save-hide-reload-restore');
    await click('回放录制'); await hasText('返回实时页面'); await until(() => (studio.replayHost as any).active?.state?.status, s => s === 'ready', 'actual native replay ready'); await mark('archive-recording-replay'); await click('返回实时页面');

    report.identity = { projectId, profileId, recordingId, fixedRevisionId: fixed.revisionId, fixedHash, dataRoot: studio.root, uiUrl: page.url() };
    assert.deepEqual(await originals(path.join(studio.root, 'runs', recordingId)), originalBefore); assert.equal(hash(await readFile(fixedFile)), fixedHash); report.immutableOriginalAndFixedUnchanged = true; assert.deepEqual(report.pageErrors, []); assert.deepEqual(report.dialogs, []); report.passed = true;
    await mark('completed'); return report;
  } catch (error) { report.error = String(error); report.stack = error instanceof Error ? error.stack : undefined; try { report.failureText = await text(); await page.screenshot({ path: path.join(proof, 'failure.renderer.png') }); } catch {} throw error; }
  finally { report.finishedAt = new Date().toISOString(); await save(); await browser.disconnect(); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }
}
