import http from 'node:http';
export async function createFixture({port=0,label='B4 same-input compatibility'}={}) {
 const requests=[];
 const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGOQKn4BAAIgAXZmNuK1AAAAAElFTkSuQmCC','base64');
 const server=http.createServer((req,res)=>{
  requests.push({at:Date.now(),path:req.url});res.setHeader('cache-control','no-store');
  const pathname=new URL(req.url,'http://127.0.0.1').pathname;
  if(pathname==='/pixel.png'){res.setHeader('content-type','image/png');res.end(pixel);return}
  if(pathname==='/archived.css'){res.setHeader('content-type','text/css');res.end('.source-banner{color:rgb(12,67,89);border-left:7px solid rgb(22,140,71);padding-left:12px;background-image:url(/pixel.png);background-repeat:no-repeat;background-position:right center;background-size:18px 18px}');return}
  if(pathname==='/missing.png'){res.writeHead(404,{'content-type':'text/plain'});res.end('deliberately absent synthetic resource');return}
  if(pathname==='/canary'||pathname==='/early-document'){res.writeHead(200,{'content-type':'text/plain'});res.end(pathname);return}
  if(pathname==='/download'){res.writeHead(200,{'content-type':'text/plain','content-disposition':`attachment; filename="${label}-download.txt"`});res.end('B4 local synthetic download policy probe');return}
  if(pathname==='/slow'){res.writeHead(200,{'content-type':'text/html;charset=utf-8'});res.write('<!doctype html><title>B4 bounded slow document</title><h1>Slow synthetic loading</h1>');const timer=setTimeout(()=>res.end('<p>finished</p>'),15000);res.on('close',()=>clearTimeout(timer));return}
  const secondary=pathname==='/second';
  res.setHeader('content-type','text/html;charset=utf-8');res.end(`<!doctype html><html data-early-phase="created"><head><meta charset="utf-8"><title>${label} ${secondary?'Second Page':'Replay Source'}</title><script>const b4DocumentToken=crypto.randomUUID();window.b4ReadDocumentToken=()=>b4DocumentToken;document.documentElement.dataset.earlyPhase='inline-before-body';fetch('/early-document?path='+encodeURIComponent(location.pathname)).catch(()=>{});</script><link rel="stylesheet" href="/archived.css"><style>body{font:20px system-ui;padding:28px;background:#f4f7fa}main{max-width:760px;background:white;padding:20px;border:2px solid #678}td{padding:12px;border:1px solid #bbb}button{font:inherit;margin:8px;padding:8px}#amount{font-weight:bold;color:#164c84}img{width:24px;height:24px}</style></head><body><main><h1>本地合成订单${secondary?'新页面':'回放'}</h1><div id="input-probe"><button id="native-counter" onclick="const n=document.querySelector('#counter-value');n.textContent=String(Number(n.textContent)+1)">原生输入计数</button><span id="counter-value">0</span><label>输入检查<input id="native-text" aria-label="输入检查" value=""></label></div><p class="source-banner">无账号。封存后不得访问本地源页补全回放。</p><table><tr data-entity="order-one"><td>订单一</td><td id="amount" data-field="amount">12.00</td></tr><tr><td>明确空值</td><td id="empty"></td></tr></table><img id="archived-image" src="/pixel.png" alt="已归档像素"><button id="change-one" onclick="document.querySelector('#amount').textContent='13.00';document.querySelector('#ordinary-note').textContent='普通正文 bes-inline:11111111-1111-4111-8111-111111111111:7'">更新金额到 13.00</button><button id="change-two" onclick="document.querySelector('#amount').textContent='14.00';document.querySelector('#ordinary-note').textContent='普通正文 bes-inline:11111111-1111-4111-8111-111111111111:8'">更新金额到 14.00</button><button id="load-missing" onclick="const image=document.createElement('img');image.id='known-missing';image.src='/missing.png';document.querySelector('main').append(image)">加载已知缺失资源</button><p id="ordinary-note">尚未发生正文变化</p><button id="route" onclick="history.pushState({synthetic:true},'', '/route-one');document.querySelector('#route-status').textContent='route-one'">同文档路由</button><p id="route-status">initial</p><a id="normal-link" href="/clicked">同页合成链接</a><a id="new-page" target="_blank" href="/second">打开合成新页面</a><a id="download" href="/download">合成下载</a><a id="historical-link" href="/canary">历史链接不应导航</a><form action="/canary"><button type="submit">历史表单不应提交</button></form></main></body></html>`)
 });
 await new Promise(r=>server.listen(port,'127.0.0.1',r));
 return{server,requests,label,downloadFilename:label+'-download.txt',url:'http://127.0.0.1:'+server.address().port,close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r))}};
}
