import assert from 'node:assert/strict';
export const delay=ms=>new Promise(r=>setTimeout(r,ms));
const usable=e=>e&&e.getClientRects().length&&!e.closest('[hidden],[inert],fieldset[disabled]')&&!e.disabled;
export async function until(fn,accept,label,timeout=20000){const end=Date.now()+timeout;while(Date.now()<end){const x=await fn();if(accept(x))return x;await delay(100)}throw Error('Timeout: '+label)}
export async function element(page,kind,name){await page.bringToFront();return page.waitForFunction((kind,name)=>{const ok=e=>e&&e.getClientRects().length&&!e.closest('[hidden],[inert],fieldset[disabled]')&&!e.disabled;if(kind==='button')return [...document.querySelectorAll('button')].find(e=>ok(e)&&(e.textContent.trim()===name||e.getAttribute('aria-label')===name));if(kind==='label')return [...document.querySelectorAll('input,textarea,select')].find(e=>ok(e)&&e.getAttribute('aria-label')===name)||[...document.querySelectorAll('label')].filter(ok).find(e=>e.firstChild?.textContent.trim()===name)?.querySelector('input,textarea,select');return [...document.querySelectorAll('summary')].find(e=>ok(e)&&e.textContent.trim().startsWith(name));},{timeout:20000},kind,name)}
export async function hit(page,h){await h.evaluate(e=>e.scrollIntoView({block:'center',inline:'nearest'}));assert(await h.evaluate(e=>{const r=e.getBoundingClientRect(),p=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.width>0&&r.height>0&&!!p&&(p===e||e.contains(p))}),'Visible control hit-test');await h.asElement().click()}
export async function click(page,name){await page.bringToFront();const h=await element(page,'button',name);await hit(page,h);await delay(130)}
export async function fill(page,label,text){await page.bringToFront();const h=await element(page,'label',label);await hit(page,h);await page.keyboard.down('Control');await page.keyboard.press('a');await page.keyboard.up('Control');await page.keyboard.press('Backspace');if(text)await h.asElement().type(text);assert.equal(await h.evaluate(e=>e.value),text)}
export async function select(page,label,match){const h=await element(page,'label',label);const chosen=await h.evaluate((e,m)=>{const opts=[...e.options].filter(o=>!o.disabled);const exact=opts.findIndex(o=>o.value===m);const index=exact>=0?exact:opts.findIndex(o=>o.textContent.includes(m));return{index,value:opts[index]?.value}},match);assert(chosen.index>=0,'Option exists: '+label);await h.asElement().select(chosen.value);await delay(150);assert.equal(await h.evaluate(e=>e.value),chosen.value)}
export async function disclose(page,name){const h=await element(page,'summary',name);if(!await h.evaluate(e=>e.parentElement.open))await hit(page,h)}
export async function hasText(page,text){await page.waitForFunction(t=>document.body.innerText.includes(t),{timeout:20000},text)}
export async function selectCard(page,title){await disclose(page,'保存点列表');const h=await page.waitForFunction(t=>[...document.querySelectorAll('.material-card-list button')].find(e=>e.textContent.startsWith(t)&&e.getClientRects().length),{timeout:15000},title);await hit(page,h);await delay(150)}

export async function exactPositionOption(page,label,seq){
 const h=await element(page,'label',label);const value=await h.evaluate((e,seq)=>[...e.options].find(o=>new RegExp('事件 #'+seq+'(?: \\u00b7|$)').test(o.textContent))?.value,seq);assert(value!==undefined,'Exact source event exists '+seq);await select(page,label,value);
}
