// @vitest-environment jsdom
import React from 'react';
import { afterEach,expect,it,vi } from 'vitest';
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { ManagedBrowserToolbar } from '@/renderer/components/managed-browser-toolbar';
import type { BrowserSessionStatus } from '@/main/browser/browser-controls';
afterEach(cleanup);
const session=():BrowserSessionStatus=>({sessionId:'session',projectId:'project',profileId:'profile',controller:'human',leaseEpoch:3,locked:false,selectedPageId:'page',closedPageCount:0,downloads:[],pages:[{pageId:'page',targetId:'target',webContentsId:1,generation:4,url:'https://example.test/',title:'Example',inspecting:false,canGoBack:false,canGoForward:false,loading:false,zoomFactor:1}]});
it('projects real disabled navigation state and keeps an in-progress address across background refresh',()=>{const state=session(),call=vi.fn(async()=>{}),refresh=vi.fn();const view=render(<ManagedBrowserToolbar session={state} call={call} refresh={refresh}/>);expect((screen.getByRole('button',{name:'后退'}) as HTMLButtonElement).disabled).toBe(true);const address=screen.getByRole('textbox',{name:'网页地址'}) as HTMLInputElement;fireEvent.focus(address);fireEvent.change(address,{target:{value:'https://next.test/'}});view.rerender(<ManagedBrowserToolbar session={{...state,pages:[{...state.pages[0],url:'https://redirect.test/'}]}} call={call} refresh={refresh}/>);expect(address.value).toBe('https://next.test/');fireEvent.click(screen.getByRole('button',{name:'前往'}));expect(call).toHaveBeenCalledWith('browserCommand',expect.objectContaining({command:'navigate',sessionId:'session',leaseEpoch:3,pageId:'page',targetId:'target',generation:4,url:'https://next.test/'}));});
it('new page remains discoverable after closing the last tab and carries only session identity',()=>{const state={...session(),pages:[],selectedPageId:''},call=vi.fn(async()=>{});render(<ManagedBrowserToolbar session={state} call={call} refresh={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'新标签'}));expect(call).toHaveBeenCalledWith('browserCommand',{sessionId:'session',leaseEpoch:3,command:'new'});expect(screen.getByText(/当前没有标签/)).toBeTruthy();});
it('load stop and dialog cancel are independent visible commands under the same exact page identity',()=>{const state=session();state.pages[0]={...state.pages[0],loading:true,dialog:{id:'dialog',type:'confirm',message:'Submit?',defaultValue:''}};const call=vi.fn(async()=>{});render(<ManagedBrowserToolbar session={state} call={call} refresh={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:'停止加载'}));fireEvent.click(screen.getByRole('button',{name:'取消'}));expect(call.mock.calls.map(args=>(args as any)[1].command)).toEqual(['stop','dialog']);expect(call).toHaveBeenLastCalledWith('browserCommand',expect.objectContaining({dialogId:'dialog',accept:false}));});
it('a late old-session error cannot overwrite a newly selected session context',async()=>{let reject!:(reason:unknown)=>void;const call=vi.fn(()=>new Promise((_,failure)=>{reject=failure;})),refresh=vi.fn(),state=session();const view=render(<ManagedBrowserToolbar session={state} call={call} refresh={refresh}/>);fireEvent.click(screen.getByRole('button',{name:'刷新'}));view.rerender(<ManagedBrowserToolbar session={{...state,sessionId:'replacement'}} call={call} refresh={refresh}/>);reject(new Error('old failure'));await waitFor(()=>expect(refresh).toHaveBeenCalled());expect(screen.queryByText(/old failure/)).toBeNull();});
