import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { expect, it, vi } from 'vitest';
vi.mock('electron',()=>({app:{},session:{},BrowserWindow:class{},WebContentsView:class{}}));
import { Studio } from '@/main/services/studio';
import { ProjectMaterials } from '@/main/services/project-materials';
import { FileMaterialService } from '@/materials';
async function fixture(){
 await mkdir('output/e-regression',{recursive:true});const root=await mkdtemp(path.resolve('output/e-regression/capture-'));
 await writeFile(path.join(root,'workspace.json'),JSON.stringify({schemaVersion:1,projects:[{id:'project'}]}));await mkdir(path.join(root,'runs','recording'),{recursive:true});await writeFile(path.join(root,'runs','recording','manifest.json'),JSON.stringify({id:'recording',projectId:'project',schemaVersion:2}));
 const materials=new ProjectMaterials(root);Object.defineProperty(materials,'service',{value:new FileMaterialService(root,{position:async()=> 'reliable',target:async()=>true})});const draft=await materials.service.createDraft('project','human');
 const position={recordingId:'recording',pageId:'page',documentId:'doc',streamEpoch:'epoch',eventSeq:1,sourceTimeMs:1000};const target={kind:'dom-node',position,frameId:'top',mirrorScopeId:'mirror',nodeId:1};
 const page={pageId:'page',targetId:'target',navigationGeneration:1,capture:{inspecting:true,selectionId:'selection',snapshotPosition:async()=>position}};
 const run={id:'recording',projectId:'project',controller:'human',leaseEpoch:1,pages:new Map([['page',page]]),selectedPageId:'page',selection:{sample:{ref:target},selectionId:'selection',generation:1},store:{flush:async()=>{}}};
 const receipts:any[]=[];const studio=Object.create(Studio.prototype) as any;Object.assign(studio,{root,active:run,browser:{id:'session',runtime:run},materials,current:()=>page,reader:()=>({checkpoints:async()=>({items:receipts})}),checkpoint:vi.fn(async(_body:any,options:any)=>{const receipt={id:'receipt-'+receipts.length,pageId:options.pageId,navigationGeneration:_body.generation,captureConsistency:'consistent',metadata:{authoring:structuredClone(options.authoring)}};receipts.push(receipt);return receipt;})});
 const body={projectId:'project',draftId:draft.draftId,operationId:'operation',selection:true,purpose:'field',fieldId:'field',selectionId:'selection',pageId:'page',generation:1,leaseEpoch:1};return {studio,body,page,root,materials,draft,receipts,target};
}
it('queries an associated operation after a lost response without another receipt/card',async()=>{const f=await fixture();await f.studio.captureAndAuthor(f.body);const result=await f.studio.authoringOperation(f.body);expect(result.stage).toBe('associated');expect(result.purpose).toBe('field');expect(result.fieldId).toBe('field');await f.studio.captureAndAuthor(f.body);expect(f.receipts).toHaveLength(1);expect(f.receipts[0]).toMatchObject({pageId:'page',navigationGeneration:1});expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});
it('receipt-only retry preserves purpose/target and associates once',async()=>{const f=await fixture();const author=vi.spyOn(f.materials,'authorReceipt');author.mockRejectedValueOnce(new Error('disk unavailable'));const first=await f.studio.captureAndAuthor(f.body);expect(first.stage).toBe('receipt-saved');const saved=await f.studio.authoringOperation(f.body);expect(saved.receiptId).toBe(first.receiptId);f.page.navigationGeneration++;const result=await f.studio.captureAndAuthor(f.body);expect(result).toMatchObject({stage:'associated',purpose:'field',fieldId:'field',target:f.target});expect(f.receipts).toHaveLength(1);expect(f.receipts[0]).toMatchObject({pageId:'page',navigationGeneration:1});expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});
it('rejects intent retry after navigation before acquisition, retaining the intent',async()=>{const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('capture unavailable'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow('capture unavailable');f.page.navigationGeneration++;const result=await f.studio.captureAndAuthor(f.body);expect(result.stage).toBe('source-expired');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect(f.receipts).toHaveLength(0);expect(JSON.parse(await readFile(path.join(f.root,'authoring','operation.json'),'utf8')).stage).toBe('source-expired');});
it('a stored operation cannot be reused for another draft or changed purpose',async()=>{const f=await fixture();await f.studio.captureAndAuthor(f.body);await expect(f.studio.captureAndAuthor({...f.body,draftId:'other'})).rejects.toThrow(/identity|draft/i);await expect(f.studio.captureAndAuthor({...f.body,purpose:'observation',selection:false})).rejects.toThrow(/identity|purpose/i);});

it('navigation during acquisition keeps the raw receipt but never associates the old target',async()=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);f.page.navigationGeneration++;return receipt;});const result=await f.studio.captureAndAuthor(f.body);expect(result.stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');await f.studio.captureAndAuthor(f.body);expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});
it('mixed raw receipt followed by flush failure is recovered as expired, never associated',async()=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);receipt.captureConsistency='mixed';f.page.navigationGeneration++;return receipt;});f.studio.active.store.flush=async()=>{throw new Error('flush failed');};await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow('flush failed');expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});
it('failed acquisition without raw data is queryable as not captured and accepts a fresh selection',async()=>{const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('capture failed'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();expect((await f.studio.authoringOperation(f.body)).stage).toBe('not-captured');const next={...f.body,operationId:'new-operation'};const result=await f.studio.captureAndAuthor(next);expect(result.stage).toBe('associated');expect(f.receipts).toHaveLength(1);expect(f.receipts[0].metadata.authoring.operationId).toBe('new-operation');expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});

it.each(['unknown','missing'])('unverified %s receipt source cannot become a card',async mode=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);if(mode==='unknown')receipt.captureConsistency='unknown';else delete receipt.pageId;return receipt;});f.studio.active.store.flush=async()=>{throw new Error('flush failed');};await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});
