import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { expect, it, vi } from 'vitest';
vi.mock('electron',()=>({app:{},session:{},BrowserWindow:class{},WebContentsView:class{}}));
import { Studio } from '@/main/services/studio';
import { ProjectMaterials } from '@/main/services/project-materials';
import { FileMaterialService } from '@/materials';
import { EvidenceStore } from '@/evidence/store';
import { EvidenceReader } from '@/evidence/reader';
async function fixture(){
 await mkdir('output/e-regression',{recursive:true});const root=await mkdtemp(path.resolve('output/e-regression/capture-'));
 await writeFile(path.join(root,'workspace.json'),JSON.stringify({schemaVersion:1,projects:[{id:'project'}]}));await mkdir(path.join(root,'runs','recording'),{recursive:true});await writeFile(path.join(root,'runs','recording','manifest.json'),JSON.stringify({id:'recording',projectId:'project',schemaVersion:2}));
 const materials=new ProjectMaterials(root);Object.defineProperty(materials,'service',{value:new FileMaterialService(root,{position:async()=> 'reliable',target:async()=>true})});const draft=await materials.service.createDraft('project','human');
 const position={recordingId:'recording',pageId:'page',documentId:'doc',streamEpoch:'epoch',eventSeq:1,sourceTimeMs:1000};const target={kind:'dom-node',position,frameId:'top',mirrorScopeId:'mirror',nodeId:1};
 const page={pageId:'page',targetId:'target',navigationGeneration:1,capture:{inspecting:true,selectionId:'selection',snapshotPosition:async()=>position}};
 const run={id:'recording',projectId:'project',controller:'human',leaseEpoch:1,pages:new Map([['page',page]]),selectedPageId:'page',selection:{sample:{ref:target},selectionId:'selection',generation:1},store:{flush:async()=>{}}};
 const receipts:any[]=[];const studio=Object.create(Studio.prototype) as any;Object.assign(studio,{instanceId:'app-instance',authoringTasks:new Map(),root,active:run,browser:{id:'session',runtime:run},materials,current:()=>page,reader:()=>({checkpoints:async()=>({items:receipts})}),checkpoint:vi.fn(async(_body:any,options:any)=>{const receipt={id:'receipt-'+receipts.length,pageId:options.pageId,navigationGeneration:_body.generation,captureConsistency:'consistent',metadata:{authoring:structuredClone(options.authoring)}};receipts.push(receipt);return receipt;})});
 const body={projectId:'project',draftId:draft.draftId,operationId:'operation',selection:true,purpose:'field',fieldId:'field',selectionId:'selection',pageId:'page',generation:1,leaseEpoch:1};return {studio,body,page,root,materials,draft,receipts,target};
}
it('queries an associated operation after a lost response without another receipt/card',async()=>{const f=await fixture();await f.studio.captureAndAuthor(f.body);const result=await f.studio.authoringOperation(f.body);expect(result.stage).toBe('associated');expect(result.purpose).toBe('field');expect(result.fieldId).toBe('field');await f.studio.captureAndAuthor(f.body);expect(f.receipts).toHaveLength(1);expect(f.receipts[0]).toMatchObject({pageId:'page',navigationGeneration:1});expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});
it('receipt-only retry preserves purpose/target and associates once',async()=>{const f=await fixture();const author=vi.spyOn(f.materials,'authorReceipt');author.mockRejectedValueOnce(new Error('disk unavailable'));const first=await f.studio.captureAndAuthor(f.body);expect(first.stage).toBe('receipt-saved');const saved=await f.studio.authoringOperation(f.body);expect(saved.receiptId).toBe(first.receiptId);f.page.navigationGeneration++;const result=await f.studio.captureAndAuthor(f.body);expect(result).toMatchObject({stage:'associated',purpose:'field',fieldId:'field',target:f.target});expect(f.receipts).toHaveLength(1);expect(f.receipts[0]).toMatchObject({pageId:'page',navigationGeneration:1});expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});
it('rejects intent retry after navigation before acquisition, retaining the intent',async()=>{const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('capture unavailable'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow('capture unavailable');f.page.navigationGeneration++;const result=await f.studio.captureAndAuthor(f.body);expect(result.stage).toBe('source-expired');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect(f.receipts).toHaveLength(0);expect(JSON.parse(await readFile(path.join(f.root,'authoring','operation.json'),'utf8')).stage).toBe('source-expired');});
it('a stored operation cannot be reused for another draft or changed purpose',async()=>{const f=await fixture();await f.studio.captureAndAuthor(f.body);await expect(f.studio.captureAndAuthor({...f.body,draftId:'other'})).rejects.toThrow(/identity|draft/i);await expect(f.studio.captureAndAuthor({...f.body,purpose:'observation',selection:false})).rejects.toThrow(/identity|purpose/i);});

it('navigation during acquisition keeps the raw receipt but never associates the old target',async()=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);f.page.navigationGeneration++;return receipt;});const result=await f.studio.captureAndAuthor(f.body);expect(result.stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');await f.studio.captureAndAuthor(f.body);expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});
it('mixed raw receipt followed by flush failure is recovered as expired, never associated',async()=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);receipt.captureConsistency='mixed';f.page.navigationGeneration++;return receipt;});f.studio.active.store.flush=async()=>{throw new Error('flush failed');};await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow('flush failed');expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});
it('failed acquisition without raw data is queryable as not captured and accepts a fresh selection',async()=>{const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('capture failed'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();expect((await f.studio.authoringOperation(f.body)).stage).toBe('not-captured');const next={...f.body,operationId:'new-operation'};const result=await f.studio.captureAndAuthor(next);expect(result.stage).toBe('associated');expect(f.receipts).toHaveLength(1);expect(f.receipts[0].metadata.authoring.operationId).toBe('new-operation');expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);});

it.each(['unknown','missing'])('unverified %s receipt source cannot become a card',async mode=>{const f=await fixture();const acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{const receipt=await acquire(...args);if(mode==='unknown')receipt.captureConsistency='unknown';else delete receipt.pageId;return receipt;});f.studio.active.store.flush=async()=>{throw new Error('flush failed');};await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();expect((await f.studio.authoringOperation(f.body)).stage).toBe('source-expired');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('source-expired');expect(f.receipts).toHaveLength(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);});

it('orphan acquiring without receipt becomes interrupted after app restart and preserves partial artifacts',async()=>{
 const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('stop after intent'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();const file=path.join(f.root,'authoring','operation.json'),operation=JSON.parse(await readFile(file,'utf8'));operation.stage='acquiring';await writeFile(file,JSON.stringify(operation));await writeFile(path.join(f.root,'partial-artifact.bin'),'retained artifact');f.studio.instanceId='new-app';
 expect(await f.studio.authoringOperation(f.body)).toMatchObject({stage:'interrupted',operationId:'operation'});expect(JSON.parse(await readFile(file,'utf8')).stage).toBe('interrupted');expect(await readFile(path.join(f.root,'partial-artifact.bin'),'utf8')).toBe('retained artifact');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('interrupted');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect((await f.studio.captureAndAuthor({...f.body,operationId:'fresh'})).stage).toBe('associated');
});

it('receipt read failure stays unknown and cannot trigger another acquisition',async()=>{
 const f=await fixture();f.studio.checkpoint.mockRejectedValueOnce(new Error('stop after intent'));await expect(f.studio.captureAndAuthor(f.body)).rejects.toThrow();const file=path.join(f.root,'authoring','operation.json'),operation=JSON.parse(await readFile(file,'utf8'));operation.stage='acquiring';await writeFile(file,JSON.stringify(operation));f.studio.instanceId='new-app';f.studio.reader=()=>({checkpoints:async()=>{throw new Error('source disk unreadable');}});
 expect(await f.studio.authoringOperation(f.body)).toMatchObject({stage:'unknown',reason:expect.stringContaining('source disk unreadable')});expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('unknown');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect(JSON.parse(await readFile(file,'utf8')).stage).not.toBe('not-captured');
});

it('active acquisition survives status polling and concurrent retry without another checkpoint',async()=>{
 const f=await fixture();let release!:()=>void;const wait=new Promise<void>(resolve=>release=resolve),acquire=f.studio.checkpoint.getMockImplementation();f.studio.checkpoint.mockImplementationOnce(async(...args:any[])=>{await wait;return acquire(...args);});
 const first=f.studio.captureAndAuthor(f.body);await vi.waitFor(()=>expect(f.studio.checkpoint).toHaveBeenCalledTimes(1));const operation=JSON.parse(await readFile(path.join(f.root,'authoring','operation.json'),'utf8'));expect(operation).toMatchObject({appInstanceId:'app-instance',source:{sessionId:'session'},stage:'acquiring'});
 expect((await f.studio.authoringOperation(f.body)).stage).toBe('acquiring');const second=f.studio.captureAndAuthor(f.body);expect((await f.studio.authoringOperation(f.body)).stage).toBe('acquiring');release();const results=await Promise.all([first,second]);expect(results.map(result=>result.card.id)).toEqual([results[0].card.id,results[0].card.id]);expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);
});

it('an in-flight operation before its journal exists is still acquiring',async()=>{
 const f=await fixture();let release!:(value:unknown)=>void;const positionReady=new Promise(resolve=>release=resolve);f.page.capture.snapshotPosition=()=>positionReady as any;const body={...f.body,selection:false,purpose:'observation'},pending=f.studio.captureAndAuthor(body);
 await vi.waitFor(()=>expect(f.studio.authoringTasks.size).toBe(1));expect((await f.studio.authoringOperation(body)).stage).toBe('acquiring');release(f.target.position);expect((await pending).stage).toBe('associated');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);
});

it.each(['intent','acquiring','associated'])('restarts from %s journal with an existing raw receipt without recapture',async stage=>{
 const f=await fixture();if(stage!=='associated')vi.spyOn(f.materials,'authorReceipt').mockRejectedValueOnce(new Error('association interrupted'));
 await f.studio.captureAndAuthor(f.body);const file=path.join(f.root,'authoring','operation.json'),operation=JSON.parse(await readFile(file,'utf8'));delete operation.receiptId;operation.stage=stage==='intent'?'not-captured':'acquiring';await writeFile(file,JSON.stringify(operation));f.studio.instanceId='restarted';f.studio.browser=undefined;f.studio.active=undefined;
 const recovered=await f.studio.authoringOperation(f.body);expect(recovered.stage).toBe(stage==='associated'?'associated':'receipt-saved');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('associated');expect(f.receipts).toHaveLength(1);expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(1);
});

it.each(['identity','budget'])('unverified %s receipt lookup remains unknown instead of declaring no capture',async mode=>{
 const f=await fixture();vi.spyOn(f.materials,'authorReceipt').mockRejectedValueOnce(new Error('association interrupted'));await f.studio.captureAndAuthor(f.body);const file=path.join(f.root,'authoring','operation.json'),operation=JSON.parse(await readFile(file,'utf8'));delete operation.receiptId;operation.stage='acquiring';await writeFile(file,JSON.stringify(operation));f.studio.instanceId='restarted';
 if(mode==='identity')f.receipts[0].metadata.authoring.draftId='wrong-draft';else f.studio.reader=()=>({checkpoints:async()=>({items:[{id:'receipt',readStatus:'record-exceeds-query-budget'}],outputTruncated:true})});
 expect((await f.studio.authoringOperation(f.body)).stage).toBe('unknown');expect((await f.studio.captureAndAuthor(f.body)).stage).toBe('unknown');expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect((await f.materials.service.getDraft('project',f.draft.draftId)).content.checkpoints).toHaveLength(0);
});

it('recovers a projected receipt from the real evidence store after reopening without modifying originals',async()=>{
 const f=await fixture(),runDir=path.join(f.root,'raw-original');const store=await EvidenceStore.create(runDir,{id:'recording',projectId:'project',kind:'demonstrate',mode:'synthetic',objective:'Authoring recovery'});
 f.studio.active.store=store;f.studio.reader=()=>new EvidenceReader(runDir);f.studio.checkpoint.mockImplementation(async(body:any,options:any)=>store.appendCheckpoint({key:'sample',title:'Synthetic receipt',captureStartedAt:new Date().toISOString(),captureEndedAt:new Date().toISOString(),captureConsistency:'consistent',pageId:options.pageId,navigationGeneration:body.generation,artifactRefs:[],metadata:{authoring:structuredClone(options.authoring)}}));vi.spyOn(f.materials,'authorReceipt').mockRejectedValueOnce(new Error('association interrupted'));
 const captured=await f.studio.captureAndAuthor(f.body);expect(captured.stage).toBe('receipt-saved');await store.close();const journal=path.join(f.root,'authoring','operation.json'),operation=JSON.parse(await readFile(journal,'utf8'));delete operation.receiptId;operation.stage='acquiring';await writeFile(journal,JSON.stringify(operation));f.studio.instanceId='restart';f.studio.browser=undefined;f.studio.active=undefined;
 const reopened=await EvidenceStore.open(runDir);await reopened.close();const reader=new EvidenceReader(runDir),original=await reader.checkpoints({limit:100,maxBytes:32768});expect((await f.studio.authoringOperation(f.body)).stage).toBe('receipt-saved');const result=await f.studio.captureAndAuthor(f.body);expect(result).toMatchObject({stage:'associated',receiptId:captured.receiptId,target:f.target});expect(f.studio.checkpoint).toHaveBeenCalledTimes(1);expect((await reader.checkpoints({limit:100,maxBytes:32768})).items).toEqual(original.items);
});
