import { EventEmitter } from 'node:events';
import { mkdtemp,writeFile,open } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { expect,it,vi } from 'vitest';
import { SessionDownloads } from '@/main/browser/downloads';
function item(){return Object.assign(new EventEmitter(),{getFilename:()=> 'report.csv',getTotalBytes:()=>6,getReceivedBytes:()=>6,getURL:()=> 'https://example.test/report.csv',getMimeType:()=> 'text/csv',setSavePath:vi.fn(),cancel:vi.fn()});}
async function fixture(){const session=new EventEmitter(),directory=await mkdtemp(path.join(os.tmpdir(),'bes-browser-download-')),downloads=new SessionDownloads(session as any,directory,wc=>wc.id===1?'page':undefined,vi.fn());await downloads.start();const start=()=>{const download=item(),event={preventDefault:vi.fn()};session.emit('will-download',event,download,{id:1});return download;};return {downloads,session,start};}
it('downloads work without recording, retain location and cancel without executing the file',async()=>{const f=await fixture(),download=f.start(),status=f.downloads.list()[0];expect(status.state).toBe('progressing');expect(status.recordingId).toBeUndefined();expect(download.setSavePath).toHaveBeenCalledWith(status.path);f.downloads.cancel(status.id);expect(download.cancel).toHaveBeenCalledOnce();download.emit('done',{},'cancelled');expect(f.downloads.list()[0].state).toBe('cancelled');expect(()=>f.downloads.location(status.id)).toThrow();await f.downloads.dispose();expect(f.session.listenerCount('will-download')).toBe(0);});
it('sealing a recording excludes unfinished evidence but preserves the session download',async()=>{const f=await fixture(),store={appendEvent:vi.fn(async()=>{}),putArtifact:vi.fn(async()=>({id:'artifact',captureStatus:'captured'}))};f.downloads.beginRecording('recording',store as any);const download=f.start();await f.downloads.finishRecording();expect(download.cancel).not.toHaveBeenCalled();expect(f.downloads.list()[0].evidence).toBe('excluded');expect(store.appendEvent).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({reason:'download-not-finished-at-recording-end'})}));store.appendEvent.mockClear();download.emit('done',{},'completed');expect(store.putArtifact).not.toHaveBeenCalled();expect(store.appendEvent).not.toHaveBeenCalled();expect(f.downloads.location(f.downloads.list()[0].id)).toContain('report.csv');await f.downloads.dispose();});
it.each([false,true])('finished recording download uses bounded evidence import (over budget=%s)',async large=>{const f=await fixture(),store={appendEvent:vi.fn(async()=>{}),putArtifact:vi.fn(async(body:any)=>({id:'artifact',captureStatus:body.captureStatus??'captured'}))};f.downloads.beginRecording('recording',store as any);const download=f.start(),status=f.downloads.list()[0];if(large){const file=await open(status.path,'w');await file.truncate(64*1024*1024+1);await file.close();}else await writeFile(status.path,'a,b\n1,2');download.emit('done',{},'completed');await f.downloads.finishRecording();expect(store.putArtifact).toHaveBeenCalledOnce();expect(store.putArtifact.mock.calls[0][0].data===undefined).toBe(large);expect(f.downloads.list()[0].evidence).toBe(large?'excluded':'imported');expect(f.downloads.location(status.id)).toBe(status.path);await f.downloads.dispose();});
