import { EventEmitter } from 'node:events';
import { afterEach,expect,it,vi } from 'vitest';
vi.mock('electron',()=>({app:{},session:{},Menu:{buildFromTemplate:vi.fn()},clipboard:{},shell:{showItemInFolder:vi.fn()},WebContentsView:class{}}));
import { Studio } from '@/main/services/studio';
import { browserUrl,browserShortcut } from '@/main/browser/browser-controls';
function fixture(){
  const wc:any=Object.assign(new EventEmitter(),{id:10,isDestroyed:()=>false,getURL:()=> 'https://example.test/',getTitle:()=> 'Example',isLoadingMainFrame:()=>false,getZoomFactor:()=>1,setZoomFactor:vi.fn(),loadURL:vi.fn(async()=>{}),stop:vi.fn(),findInPage:vi.fn(),stopFindInPage:vi.fn(),setWindowOpenHandler:vi.fn(),navigationHistory:{canGoBack:()=>false,canGoForward:()=>false,goBack:vi.fn(),goForward:vi.fn()},debugger:{attach:vi.fn(),detach:vi.fn(),sendCommand:vi.fn(async()=>({targetInfo:{targetId:'target-new'}}))}});
  const native={webContents:wc};const frame={},observed:any=Object.assign(new EventEmitter(),{mainFrame:()=>frame});
  const old:any={pageId:'old',targetId:'target-old',webContentsId:1,navigationGeneration:2,view:{webContents:wc},page:observed};
  const runtime:any={projectId:'project',profileId:'profile',session:{},pages:new Map([['old',old]]),selectedPageId:'old',controller:'human',locked:false,leaseEpoch:4,execution:'ready'};
  const studio:any=Object.create(Studio.prototype);Object.assign(studio,{browser:{id:'session',runtime},queue:Promise.resolve(),closedPages:[],onChanged:vi.fn(),window:{add:vi.fn(),remove:vi.fn((view:any)=>view.webContents.emit('destroyed')),lock:vi.fn(),show:vi.fn()},observer:{waitForTarget:vi.fn(async()=>({page:async()=>observed}))},tasks:{addPage:vi.fn()},pageAudit:vi.fn(async()=>{}),recordForeground:vi.fn(async()=>{})});
  return {studio,runtime,old,wc,native,observed,body:{sessionId:'session',leaseEpoch:4,pageId:'old',targetId:'target-old',generation:2}};
}
afterEach(()=>vi.restoreAllMocks());
it('normalizes explicit hostnames but rejects executable/local/credential addresses',()=>{expect(browserUrl('example.test/path')).toBe('https://example.test/path');expect(browserUrl('localhost:8080')).toBe('https://localhost:8080/');for(const url of ['javascript:alert(1)','file:///secret','C:\\secret','https://user:password@example.test/','some search words'])expect(()=>browserUrl(url)).toThrow();});
it('browser command validates the whole page identity, controller and selection scope',async()=>{const f=fixture();for(const bad of [{sessionId:'other'},{leaseEpoch:3},{targetId:'other'},{generation:1}])await expect(f.studio.browserCommand({...f.body,...bad,command:'stop'})).rejects.toThrow();f.runtime.controller='agent';await expect(f.studio.browserCommand({...f.body,command:'stop'})).rejects.toThrow();f.runtime.controller='human';f.studio.active=f.runtime;f.old.capture={inspecting:true};await expect(f.studio.browserCommand({...f.body,command:'navigate',url:'https://example.test/'})).rejects.toThrow();expect(f.wc.stop).not.toHaveBeenCalled();expect(f.wc.loadURL).not.toHaveBeenCalled();});
it('slow human navigation does not hold Stop and neither operation stops the recording',async()=>{const f=fixture();f.wc.loadURL.mockImplementation(()=>new Promise(()=>{}));f.runtime.capture='recording';await f.studio.browserCommand({...f.body,command:'navigate',url:'example.test/slow'});await f.studio.browserCommand({...f.body,command:'stop'});expect(f.wc.stop).toHaveBeenCalledOnce();expect(f.runtime.capture).toBe('recording');expect(f.runtime.pages.size).toBe(1);});
it('find and zoom target only the identified selected page, with a zoom audit',async()=>{const f=fixture();await f.studio.browserCommand({...f.body,command:'find',text:'amount',findNext:true,forward:false});expect(f.wc.findInPage).toHaveBeenCalledWith('amount',{findNext:true,forward:false});await f.studio.browserCommand({...f.body,command:'zoom',zoomFactor:1.5});expect(f.wc.setZoomFactor).toHaveBeenCalledWith(1.5);expect(f.studio.pageAudit.mock.calls[0][1]).toMatchObject({type:'page-zoom',pageId:'old',navigationGeneration:2});});
it('dialog response is explicit and stale dialog IDs cannot confirm a later prompt',async()=>{const f=fixture(),dialog={accept:vi.fn(async()=>{}),dismiss:vi.fn(async()=>{}),type:()=> 'prompt',message:()=> 'Name',defaultValue:()=> ''};f.old.dialog={id:'dialog',value:dialog};await expect(f.studio.browserCommand({...f.body,command:'dialog',dialogId:'old',accept:true})).rejects.toThrow();await f.studio.browserCommand({...f.body,command:'dialog',dialogId:'dialog',accept:false});expect(dialog.accept).not.toHaveBeenCalled();expect(dialog.dismiss).toHaveBeenCalledOnce();expect(f.old.dialog).toBeUndefined();});
it.each(['native-add','target-wait','capture-start','authorization-registration'])('allocation failure at %s removes only its own view and restores latest owner mask',async(stage)=>{
  const f=fixture(),failure=new Error(stage),capture={start:vi.fn(async()=>{}),stop:vi.fn(async()=>{})};
  if(stage==='native-add')f.studio.window.add.mockImplementation(()=>{throw failure;});
  if(stage==='target-wait')f.studio.observer.waitForTarget.mockRejectedValue(failure);
  if(stage==='capture-start'){f.studio.active=f.runtime;f.studio.createCapture=()=>capture;capture.start.mockRejectedValue(failure);}
  if(stage==='authorization-registration'){f.runtime.controller='agent';f.studio.browserAuthorizationId='grant';f.studio.tasks.addPage.mockImplementation(()=>{throw failure;});}
  await expect(f.studio.addPage(f.runtime,'old',f.native)).rejects.toThrow(stage);
  expect([...f.runtime.pages.keys()]).toEqual(['old']);expect(f.runtime.selectedPageId).toBe('old');expect(f.studio.window.remove).toHaveBeenCalledWith(f.native);expect(f.studio.window.show).toHaveBeenLastCalledWith(f.old.view);expect(f.studio.window.lock).toHaveBeenLastCalledWith(stage==='authorization-registration');
  if(stage==='capture-start')expect(capture.stop).toHaveBeenCalledOnce();
});
it('initial navigation failure keeps a registered retryable error page, with old page intact',async()=>{const f=fixture();const page=await f.studio.addPage(f.runtime,undefined,f.native);f.wc.loadURL.mockRejectedValue(new Error('ERR_CONNECTION_REFUSED'));f.studio.loadHumanUrl(page,'https://example.test/unavailable');await new Promise(resolve=>setImmediate(resolve));expect(f.runtime.pages.size).toBe(2);expect(f.runtime.pages.get('old')).toBe(f.old);expect(page.loadError).toMatchObject({kind:'network',url:'https://example.test/unavailable'});expect(f.studio.window.remove).not.toHaveBeenCalled();});
it('a retained empty human session can create another tab without a task grant or recording',async()=>{const f=fixture();f.runtime.pages.clear();f.runtime.selectedPageId='';f.studio.addPage=vi.fn(async()=>{f.runtime.pages.set('old',f.old);f.runtime.selectedPageId='old';return f.old;});await f.studio.browserCommand({sessionId:'session',leaseEpoch:4,command:'new'});expect(f.studio.tasks.addPage).not.toHaveBeenCalled();expect(f.studio.active).toBeUndefined();expect(f.runtime.controller).toBe('human');expect(f.runtime.leaseEpoch).toBe(5);});
it('shortcuts consume only one keyDown with correct Shift+T and no Alt alias',()=>{expect(browserShortcut({type:'keyDown',key:'T',control:true,shift:true})).toBe('reopen');expect(browserShortcut({type:'keyUp',key:'w',control:true})).toBeUndefined();expect(browserShortcut({type:'keyDown',key:'w',control:true,alt:true})).toBeUndefined();});

it('navigation beforeunload remains visible until an explicit dialog response',async()=>{const f=fixture(),page=await f.studio.addPage(f.runtime,undefined,f.native),dialog={type:()=> 'beforeunload',message:()=> 'Leave unsaved changes?',defaultValue:()=> '',accept:vi.fn(),dismiss:vi.fn()};f.observed.emit('dialog',dialog);expect(page.dialog.value).toBe(dialog);expect(dialog.accept).not.toHaveBeenCalled();expect(dialog.dismiss).not.toHaveBeenCalled();});
