import { describe, expect, it, vi } from 'vitest';
import { navigateObserved } from '@/main/browser/navigation';

function fixture(){const calls:string[]=[],document={url:'https://fixture.test/',ready:'complete',timeOrigin:123},identity={id:'frame',loaderId:'loader',url:document.url};const session={send:vi.fn(async()=>({frameTree:{frame:identity}})),detached:false,detach:vi.fn(async()=>{})};const frame={evaluate:vi.fn(async()=>document)};const page={isClosed:()=>false,createCDPSession:async()=>session,waitForNavigation:vi.fn(async()=>{calls.push('watch');}),mainFrame:()=>frame};const contents={loadURL:vi.fn(async()=>{calls.push('load');}),executeJavaScript:vi.fn(async()=>document),isDestroyed:()=>false,isLoadingMainFrame:()=>false,stop:vi.fn()};const current=vi.fn();return {calls,document,identity,session,frame,page,contents,current,run:(timeout=1000)=>navigateObserved(contents as any,page as any,document.url,current,timeout)};}
describe('native navigation observer readiness',()=>{
  it('installs observation before navigation and retries only transient stale contexts',async()=>{const f=fixture(),original=new Error('Execution context was destroyed');f.frame.evaluate.mockRejectedValueOnce(original);expect(await f.run()).toEqual({url:f.document.url});expect(f.calls).toEqual(['watch','load']);expect(f.frame.evaluate).toHaveBeenCalledTimes(2);expect(f.session.detach).toHaveBeenCalledOnce();});
  it('rejects another document even when it has the same URL',async()=>{const f=fixture();f.session.send.mockResolvedValueOnce({frameTree:{frame:f.identity}}).mockResolvedValueOnce({frameTree:{frame:{...f.identity,loaderId:'another-loader'}}});await expect(f.run()).rejects.toThrow('Navigation changed again');});
  it('preserves actual evaluation failure and target loss',async()=>{const f=fixture(),original=Object.assign(new Error('Synthetic protocol denied'),{code:'EACCES'});f.frame.evaluate.mockRejectedValueOnce(original);await expect(f.run()).rejects.toBe(original);const lost=fixture();lost.current.mockImplementationOnce(()=>{}).mockImplementation(()=>{throw new Error('Target ownership lost');});await expect(lost.run()).rejects.toThrow('Target ownership lost');expect(lost.contents.loadURL).not.toHaveBeenCalled();});
  it('bounds repeated stale contexts and retains the original cause',async()=>{const f=fixture(),original=new Error('Execution context destroyed');f.frame.evaluate.mockRejectedValue(original);await expect(f.run(60)).rejects.toMatchObject({message:'Navigation document readiness timed out',cause:original});expect(f.contents.stop).toHaveBeenCalledOnce();expect(f.session.detach).toHaveBeenCalledOnce();});
});
