import { beforeEach, describe, expect, it, vi } from 'vitest';
import { ReplayHost } from '@/main/services/replay-host';
import { replayHit } from '@/main/services/replay-presentation';

const fake=vi.hoisted(()=>({views:[] as any[],partitions:[] as any[],response:vi.fn(),load:undefined as undefined|Promise<void>,selection:undefined as undefined|Promise<boolean>}));
vi.mock('electron',()=>({session:{fromPartition:()=>{const value={setPermissionRequestHandler:vi.fn(),setPermissionCheckHandler:vi.fn(),webRequest:{onBeforeRequest:vi.fn()},on:vi.fn(),protocol:{handler:undefined as any,handle(_name:string,handler:any){this.handler=handler;},unhandle:vi.fn()}};fake.partitions.push(value);return value;}},WebContentsView:class{webContents={destroyed:false,setWindowOpenHandler:vi.fn(),on:vi.fn(),loadURL:vi.fn(()=>fake.load??Promise.resolve()),executeJavaScript:vi.fn(async(code:string)=>code.includes('window.__besSelectSequence=')?(fake.selection??true):code.includes('new rrweb.Replayer')?[]:true),isDestroyed:()=>this.webContents.destroyed,close:()=>{this.webContents.destroyed=true;},focus:vi.fn()};constructor(){fake.views.push(this);}}}));
vi.mock('@/replay/source-model',()=>({SourceModel:class{nodes=new Map();}}));
vi.mock('@/replay/rrweb-player',()=>({prepareReplayEvents:(window:any)=>({events:[{timestamp:0},...window.records.map((record:any,index:number)=>({timestamp:index+1}))],pauseOffset:window.records.length+1})}));
vi.mock('@/resources/archive',()=>({ResourceArchive:class{resolve=vi.fn();}}));
vi.mock('@/resources/replay-resources',()=>({prepareArchivedReplay:async(records:unknown)=>({records,diagnostics:[]}),OfflineResourceService:class{response=fake.response;}}));
vi.mock('../../../node_modules/rrweb/dist/rrweb.umd.cjs?raw',()=>({default:'/* fixture replay */'}));
const position={recordingId:'recording',pageId:'page',documentId:'document',streamEpoch:'epoch',sourceTimeMs:1,eventSeq:1};
function deferred<T>(){let resolve!:(v:T)=>void,reject!:(e:Error)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};}
function setup(){const window={showReplay:vi.fn(),hideReplay:vi.fn(),window:{webContents:{focus:vi.fn()}}};const service={window:vi.fn(async(end:typeof position)=>({records:Array.from({length:end.eventSeq},(_,index)=>({position:{...position,eventSeq:index+1,sourceTimeMs:index+1},event:{type:index===0?2:3,timestamp:index+1},viewport:{width:800,height:600,deviceScaleFactor:1}})),gaps:[]}))};const materials={replay:vi.fn(async()=>service)};return {host:new ReplayHost(window as any,materials as any,'fixture'),window,materials,service};}
beforeEach(()=>{fake.views=[];fake.partitions=[];fake.response.mockReset();fake.load=undefined;fake.selection=undefined;});
describe('isolated replay lifecycle',()=>{
  it('does not allow a delayed open to replace a newer native view',async()=>{const f=setup(),first=deferred<any>();f.materials.replay.mockImplementationOnce(()=>first.promise);const old=f.host.open({projectId:'project',position});const current=await f.host.open({projectId:'project',position});first.resolve(f.service);expect((await old).status).toBe('closed');expect(fake.views).toHaveLength(1);expect((await f.host.status(current.replayId)).status).toBe('ready');f.host.close();});
  it('handles destruction while shell initialization is pending',async()=>{const f=setup(),load=deferred<void>();fake.load=load.promise;const pending=f.host.open({projectId:'project',position});await vi.waitFor(()=>expect(fake.views).toHaveLength(1));f.host.close();load.reject(new Error('Destroyed during load'));expect((await pending).status).toBe('closed');expect(fake.views[0].webContents.executeJavaScript).not.toHaveBeenCalled();});
  it('does not focus or publish selection from a superseded seek',async()=>{const f=setup(),opened=await f.host.open({projectId:'project',position}),selection=deferred<boolean>();fake.selection=selection.promise;const pending=f.host.select(opened.replayId,true);await f.host.seek({projectId:'project',replayId:opened.replayId,position:{...position,eventSeq:2,sourceTimeMs:2}});selection.resolve(true);expect((await pending).selecting).toBe(false);expect(fake.views[0].webContents.focus).not.toHaveBeenCalled();f.host.close();});
  it('distinguishes corrupted and missing archive bytes with visible diagnostics',async()=>{const f=setup(),opened=await f.host.open({projectId:'project',position}),handler=fake.partitions[0].protocol.handler,id='00000000-0000-0000-0000-000000000001';fake.response.mockRejectedValueOnce(Object.assign(new Error('Archive hash mismatch'),{code:'INTEGRITY'}));expect((await handler({url:`bes-resource://archive/${id}?seek=${opened.generation}&at=${position.eventSeq}`})).status).toBe(500);fake.response.mockRejectedValueOnce(Object.assign(new Error('Missing archive bytes'),{code:'ENOENT'}));expect((await handler({url:`bes-resource://archive/${id}?seek=${opened.generation}&at=${position.eventSeq}`})).status).toBe(404);const state=await f.host.status(opened.replayId);expect(state.resources?.status).toBe('partial');expect(state.resources?.failures.map(item=>item.code)).toEqual(['INTEGRITY','ENOENT']);expect(state.error).toBeTruthy();expect(f.window.showReplay.mock.calls[0][1]).toBe(false);f.host.close();});
});
it('selects the actual element through scaled nested frame and open shadow boundaries',()=>{const target={tagName:'SPAN',getBoundingClientRect:()=>({left:4,top:6,width:10,height:8})},shadow={tagName:'DIV',shadowRoot:{elementFromPoint:()=>target}},child={tagName:'IFRAME',getBoundingClientRect:()=>({left:10,top:20,width:200,height:100}),contentWindow:{innerWidth:100,innerHeight:50},contentDocument:{elementFromPoint:()=>shadow}},frame={getBoundingClientRect:()=>({left:50,top:80,width:400,height:300}),contentWindow:{innerWidth:200,innerHeight:150},contentDocument:{elementFromPoint:()=>child}};const hit=replayHit(frame as any,100,150);expect(hit?.node).toBe(target);expect(hit?.rect).toEqual({x:86,y:144,width:40,height:32});child.contentDocument=null as any;expect(replayHit(frame as any,100,150)).toBeUndefined();});
