import { mkdir, mkdtemp, readFile } from 'node:fs/promises';
import path from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
vi.mock('electron',()=>({app:{},session:{},BrowserWindow:class{},WebContentsView:class{}}));
import { Studio } from '@/main/services/studio';
import { makeDispatch } from '@/main/services/dispatch';
import { TaskAuthorizations } from '@/main/services/task-authorization';
const all:TaskAuthorizations[]=[];afterEach(()=>{for(const task of all.splice(0))task.close();vi.useRealTimers();});
function page(id:string){let url='https://example.test/'+id;const observation=()=>({url,timeOrigin:1,ready:'complete'});const frame={evaluate:async()=>observation()};const value:any={pageId:id,targetId:'target-'+id,navigationGeneration:1,capture:{inspecting:false},view:{webContents:{isDestroyed:()=>false,getURL:()=>url,getTitle:()=>id,navigationHistory:{canGoBack:()=>false,canGoForward:()=>false},loadURL:async(next:string)=>{url=next;},executeJavaScript:async()=>observation(),isLoadingMainFrame:()=>false}},page:{url:()=>url,evaluate:vi.fn(async()=>[{tag:'button',text:id}]),isClosed:()=>false,createCDPSession:async()=>({send:async()=>({frameTree:{frame:{id:'frame',loaderId:'loader',url}}}),detach:async()=>{}}),waitForNavigation:async()=>{},mainFrame:()=>frame},setUrl:(next:string)=>{url=next;}};return value;}
async function fixture(){
 await mkdir('output/e-regression',{recursive:true});const root=await mkdtemp(path.resolve('output/e-regression/session-'));const tasks=new TaskAuthorizations();all.push(tasks);const front=page('front'),back=page('back');
 const runtime:any={projectId:'project',profileId:'profile',pages:new Map([['front',front],['back',back]]),selectedPageId:'front',controller:'agent',leaseEpoch:1,locked:false,execution:'ready'};
 const grant=await tasks.issue({projectId:'project',sessionId:'session',profileId:'profile'},{origins:['https://example.test'],pages:[front,back].map(({pageId,targetId})=>({pageId,targetId})),capabilities:['page-read','page-act','page-create'],durationMs:60000,maxOperations:100});
 const operation={targetId:back.targetId,documentEpoch:0,page:{mouse:{click:vi.fn(async()=>{})},$:vi.fn(async()=>({scrollIntoView:async()=>{},clickablePoint:async()=>({x:5,y:6}),evaluate:async()=>true,dispose:async()=>{}})),goto:vi.fn(async()=>{})},gate:{setCommandGuard:vi.fn(),quiesce:vi.fn(async()=>{}),close:vi.fn()},browser:{disconnect:vi.fn(async()=>{})}};runtime.operation=operation;
 const studio=Object.create(Studio.prototype) as any;Object.assign(studio,{root,tasks,active:undefined,browser:{id:'session',runtime},browserAuthorizationId:grant.authorizationId,queue:Promise.resolve(),projects:[{id:'project'}],profiles:[{id:'profile',projectId:'project'}],runs:[],validations:[],onChanged:vi.fn(),window:{lock:vi.fn(),show:vi.fn(),assertInputReady:vi.fn(),withBackgroundInteraction:vi.fn(async(_view:any,action:any)=>action())}});
 studio.addPage=vi.fn(async()=>{const created=page('created');runtime.pages.set(created.pageId,created);return created;});studio.closePageContents=vi.fn(async(p:any)=>{runtime.pages.delete(p.pageId);});
 const body={authorizationId:grant.authorizationId,sessionId:'session',projectId:'project',profileId:'profile',pageId:'back',generation:1,leaseEpoch:1};return {studio,root,tasks,grant,runtime,front,back,operation,body,dispatch:makeDispatch(studio)};
}
it('session-only authorization reads background/current pages, acts and creates without starting a recording',async()=>{const f=await fixture();const pages=await f.dispatch('pages',f.body,'api');expect(pages.items).toHaveLength(2);expect((await f.dispatch('snapshot',f.body,'api')).pageId).toBe('back');expect((await f.dispatch('snapshot',{...f.body,pageId:'front'},'api')).pageId).toBe('front');await f.dispatch('action',{...f.body,type:'click',selector:'#button'},'api');expect(f.operation.page.mouse.click).toHaveBeenCalledWith(5,6);const created=await f.dispatch('createPage',{...f.body,startUrl:'https://example.test/new'},'api');expect(created.pageId).toBe('created');expect(f.runtime.selectedPageId).toBe('front');expect(f.studio.window.show).not.toHaveBeenCalled();expect(f.studio.active).toBeUndefined();expect(f.studio.runs).toHaveLength(0);const audit=await readFile(path.join(f.root,'session-audit','session.jsonl'),'utf8');expect(audit).toContain('command');expect(audit).toContain('page-created');});
it.each(['old','wrong'])('never aliases historical run %s onto a live session',async runId=>{const f=await fixture();for(const method of ['pages','snapshot','action','createPage'])await expect(f.dispatch(method,{...f.body,runId,type:'click',selector:'#button',startUrl:'https://example.test/new'},'api')).rejects.toThrow(/Run|recording|run/);expect(f.operation.page.mouse.click).not.toHaveBeenCalled();expect(f.studio.addPage).not.toHaveBeenCalled();});
it('page and public state discovery filter current origin as well as page/target identity',async()=>{const f=await fixture();f.back.setUrl('https://outside.test/private');const body={...f.body,pageId:'front'};expect((await f.dispatch('pages',body,'api')).items.map((p:any)=>p.pageId)).toEqual(['front']);expect((await f.dispatch('state',body,'api')).session.pages.map((p:any)=>p.pageId)).toEqual(['front']);await expect(f.dispatch('snapshot',f.body,'api')).rejects.toMatchObject({code:'AUTHORIZATION_ORIGIN'});for(const method of ['pages','snapshot','action'])await expect(f.dispatch(method,{...f.body,type:'click',selector:'#button',url:'https://example.test/',startUrl:'https://example.test/'},'api')).rejects.toMatchObject({code:'AUTHORIZATION_ORIGIN'});await expect(f.dispatch('snapshot',{...f.body,type:'navigate',url:'https://example.test/'},'api')).rejects.toMatchObject({code:'AUTHORIZATION_ORIGIN'});expect(f.operation.page.mouse.click).not.toHaveBeenCalled();});
it('session reads reject navigation while evaluation is pending',async()=>{const f=await fixture();f.back.page.evaluate.mockImplementationOnce(async()=>{f.back.navigationGeneration++;return [];});await expect(f.dispatch('snapshot',f.body,'api')).rejects.toThrow(/navigated/);});
it('write lease, stale navigation, expired/revoked grants and cancellation reject without a new recording',async()=>{const f=await fixture();await expect(f.dispatch('action',{...f.body,type:'click',leaseEpoch:0},'api')).rejects.toThrow(/lease/);await expect(f.dispatch('action',{...f.body,type:'click',generation:0},'api')).rejects.toThrow(/generation/);const abort=new AbortController();abort.abort(new Error('cancelled'));await expect(f.dispatch('action',{...f.body,type:'click'},'api',{signal:abort.signal})).rejects.toThrow();f.tasks.revoke(f.grant.authorizationId);await expect(f.dispatch('snapshot',f.body,'api')).rejects.toThrow(/revoked/i);const g=await fixture();vi.spyOn(Date,'now').mockReturnValue(Date.now()+61000);await expect(g.dispatch('snapshot',g.body,'api')).rejects.toThrow(/expired/);vi.restoreAllMocks();expect(f.studio.active).toBeUndefined();});
it('revocation during an actual action stops its connection and returns no success',async()=>{const f=await fixture();f.operation.page.mouse.click.mockImplementationOnce(async()=>{f.tasks.revoke(f.grant.authorizationId);});await expect(f.dispatch('action',{...f.body,type:'click',selector:'#button'},'api')).rejects.toThrow();expect(f.operation.gate.close).toHaveBeenCalled();expect(f.runtime.operation).toBeUndefined();expect(f.runtime.leaseEpoch).toBe(2);});
it('created page is cleaned up if its anchor navigates before acquisition completes',async()=>{const f=await fixture();const add=f.studio.addPage.getMockImplementation();f.studio.addPage.mockImplementationOnce(async()=>{const p=await add();f.back.navigationGeneration++;return p;});await expect(f.dispatch('createPage',{...f.body,startUrl:'https://example.test/new'},'api')).rejects.toThrow();expect(f.runtime.pages.has('created')).toBe(false);});

it('session HTTP routes advertise recording independence and retain path identity, lease and idempotency checks',async()=>{
 const f=await fixture();const {startApi}=await import('@/main/api/server');const api=await startApi({root:f.root,dispatch:(method,body,_source,context)=>f.dispatch(method,body,'api',context)});const {token}=JSON.parse(await readFile(api.connectionFile,'utf8'));
 const get=async(endpoint:string)=>{const response=await fetch(api.address+endpoint,{headers:{Authorization:'Bearer '+token}});return {status:response.status,json:await response.json() as any};};
 const post=async(endpoint:string,body:any,key='key')=>{const response=await fetch(api.address+endpoint,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});return {status:response.status,json:await response.json() as any};};
 const job=async(id:string)=>{for(let i=0;i<50;i++){const result=await get('/v1/jobs/'+id+'?authorizationId='+f.grant.authorizationId);if(['succeeded','failed','cancelled'].includes(result.json.status))return result.json;await new Promise(resolve=>setTimeout(resolve,10));}throw new Error('job did not settle');};
 try{const capabilities=(await get('/v1/capabilities')).json;expect(capabilities.pageCommands.session.requiresRecording).toBe(false);expect(capabilities.pageCommands.run.requiresCurrentRecording).toBe(true);const query=new URLSearchParams({authorizationId:f.grant.authorizationId,sessionId:'forged',pageId:'back',generation:'1'});expect((await get('/v1/sessions/session/snapshot?'+query)).json.pageId).toBe('back');expect((await get('/v1/sessions/other/snapshot?'+query)).status).toBe(409);
 expect((await post('/v1/sessions/session/actions',{...f.body,type:'click',leaseEpoch:undefined},'no-lease')).status).toBe(409);expect((await post('/v1/sessions/session/actions',{...f.body,type:'click',generation:undefined},'no-generation')).status).toBe(409);
 const body={...f.body,sessionId:'forged',type:'click',selector:'#button'};const first=await post('/v1/sessions/session/actions',body);expect(first.status).toBe(202);expect((await job(first.json.jobId)).status).toBe('succeeded');const duplicate=await post('/v1/sessions/session/actions',body);expect(duplicate.json.jobId).toBe(first.json.jobId);expect(f.operation.page.mouse.click).toHaveBeenCalledTimes(1);expect((await post('/v1/sessions/session/actions',{...body,selector:'#different'})).status).toBe(409);
 const old=await post('/v1/runs/old/actions',{...f.body,runId:'current',type:'click',selector:'#button'},'old');expect((await job(old.json.jobId)).status).toBe('failed');expect(f.operation.page.mouse.click).toHaveBeenCalledTimes(1);
 }finally{await api.close();}
});
it('read-only access works under human control but writes do not',async()=>{const f=await fixture();f.runtime.controller='human';expect((await f.dispatch('snapshot',f.body,'api')).pageId).toBe('back');await expect(f.dispatch('action',{...f.body,type:'click'},'api')).rejects.toThrow(/Human owns/);expect(f.operation.page.mouse.click).not.toHaveBeenCalled();});
it('HTTP cancellation during actual page input revokes the connection and never acknowledges success',async()=>{const f=await fixture();const abort=new AbortController();f.operation.page.mouse.click.mockImplementationOnce(async()=>{abort.abort(new Error('cancel'));});await expect(f.dispatch('action',{...f.body,type:'click',selector:'#button'},'api',{signal:abort.signal})).rejects.toThrow(/Action stopped/);expect(f.operation.gate.close).toHaveBeenCalled();expect(f.runtime.operation).toBeUndefined();});
it('a late audit uses its captured session owner after the live session changes',async()=>{const f=await fixture();const previous=f.runtime;f.studio.browser={id:'replacement',runtime:{}};await f.studio.pageAudit(previous,{type:'control-conflict',source:'gate',data:{reason:'late transport response'}},'session');expect(await readFile(path.join(f.root,'session-audit','session.jsonl'),'utf8')).toContain('late transport response');await expect(readFile(path.join(f.root,'session-audit','replacement.jsonl'),'utf8')).rejects.toMatchObject({code:'ENOENT'});});
it('a stopped session never appends to its sealed recording store',async()=>{const f=await fixture();f.runtime.id='sealed-recording';f.runtime.store={appendEvent:vi.fn(async()=>{throw new Error('sealed');})};await f.dispatch('action',{...f.body,type:'click',selector:'#button'},'api');const created=await f.dispatch('createPage',{...f.body,startUrl:'https://example.test/new'},'api');expect(created.runId).toBeUndefined();await f.studio.control('human');expect(f.runtime.store.appendEvent).not.toHaveBeenCalled();const audit=await readFile(path.join(f.root,'session-audit','session.jsonl'),'utf8');expect(audit).toContain('command');expect(audit).toContain('control');});
it('trusted session grant and revoke complete the same actual read/action path without recording',async()=>{const f=await fixture();f.runtime.controller='human';f.runtime.operation=undefined;const grant=await f.studio.authorizeTask({...f.body,pageIds:['front','back'],origins:['https://example.test'],capabilities:['page-read','page-act'],durationMs:60000,maxOperations:10});f.runtime.operation=f.operation;const body={...f.body,authorizationId:grant.authorizationId,leaseEpoch:grant.leaseEpoch};expect((await f.dispatch('snapshot',body,'api')).pageId).toBe('back');await f.dispatch('action',{...body,type:'click',selector:'#button'},'api');await f.studio.revokeTask({projectId:'project',authorizationId:grant.authorizationId});expect(f.runtime.controller).toBe('human');await expect(f.dispatch('action',{...body,type:'click'},'api')).rejects.toThrow();expect(f.studio.active).toBeUndefined();const audit=await readFile(path.join(f.root,'session-audit','session.jsonl'),'utf8');expect(audit).toContain('task-authorization-issued');expect(audit).toContain('task-authorization-revoked');});
it('creating a page cancelled during acquisition removes the new page and never grants it',async()=>{const f=await fixture();const abort=new AbortController(),add=f.studio.addPage.getMockImplementation();f.studio.addPage.mockImplementationOnce(async()=>{const created=await add();abort.abort(new Error('cancel creation'));return created;});await expect(f.dispatch('createPage',{...f.body,startUrl:'https://example.test/new'},'api',{signal:abort.signal})).rejects.toThrow(/cancel/);expect(f.runtime.pages.has('created')).toBe(false);expect(f.tasks.get(f.grant.authorizationId).pages.some(page=>page.pageId==='created')).toBe(false);});
